name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - run: black --check src tests
      - run: flake8 src tests
      - run: pytest --maxfail=1 --disable-warnings -q
